// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATi-nmrNSC1HLQaccRhR_tc2QOV3_Ckig',
    appId: '1:64395569451:web:04bbb0a8825dd7591f7d6e',
    messagingSenderId: '64395569451',
    projectId: 'ulearning-app-c8c9b',
    authDomain: 'ulearning-app-c8c9b.firebaseapp.com',
    storageBucket: 'ulearning-app-c8c9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfi-_EEnzPMdw1006cJP-K53dgnsgyQs',
    appId: '1:64395569451:android:34c9507711953cc81f7d6e',
    messagingSenderId: '64395569451',
    projectId: 'ulearning-app-c8c9b',
    storageBucket: 'ulearning-app-c8c9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd26wBVzLUkNR0l5dvxDHUp0FgkZWToOY',
    appId: '1:64395569451:ios:f12f1b883c50ab191f7d6e',
    messagingSenderId: '64395569451',
    projectId: 'ulearning-app-c8c9b',
    storageBucket: 'ulearning-app-c8c9b.firebasestorage.app',
    iosBundleId: 'com.example.ulearningFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd26wBVzLUkNR0l5dvxDHUp0FgkZWToOY',
    appId: '1:64395569451:ios:f12f1b883c50ab191f7d6e',
    messagingSenderId: '64395569451',
    projectId: 'ulearning-app-c8c9b',
    storageBucket: 'ulearning-app-c8c9b.firebasestorage.app',
    iosBundleId: 'com.example.ulearningFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATi-nmrNSC1HLQaccRhR_tc2QOV3_Ckig',
    appId: '1:64395569451:web:9373c515e80dca9b1f7d6e',
    messagingSenderId: '64395569451',
    projectId: 'ulearning-app-c8c9b',
    authDomain: 'ulearning-app-c8c9b.firebaseapp.com',
    storageBucket: 'ulearning-app-c8c9b.firebasestorage.app',
  );
}
